@MediAppointment.API_HostAddress = http://localhost:5168

POST {{MediAppointment.API_HostAddress}}/api/identity/login
Content-Type: application/json
{
    "email": "caovanquan.973@gmail.com",
    "password": "Quan@2003"
}
###
